name: NNACD

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.9.9
  - pip
  - jupyterlab
  - Shapely=1.8.0
  - Cartopy
  - pygeos
  - Fiona
  - GDAL
  - pip:
      - -r requirements.txt
