LOAD_TS_PROFILE_BACKUP: False
SAVE_TS_PROFILE_BACKUP: True
REGIONS_PATH: "data/regions.geojson"
TS_PROFILE_PATH: "data/TSprofiles_intp.tar.gz"
BCN_SMOS_PATH: "data/BCN_SMOS_18D.zip"
GHRSST_PATH: "data/GHRSST/GHRSST.nc"
BATHYMETRI: "data/RTopo-2.0.1_30sec_bedrock_topography.nc"
BACKUP: "backup/tsprofiles.pkl"